seed: 42

data:
  data_path: /om2/user/gelbanna/commonvoice_data_curated.csv
  sampling_rate: 16000
  cache_file_path: ../cache_data
  num_speakers: 200

text:
  vocab_file: ./characters.txt
  pad: <pad>
  eos: <eos>
  unk: <unk>

dataloader:
  num_workers: 8
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 1

encoder:
  model_cache: ../cache_data

saganet:
  d_model: 704
  num_head: 8
  dim_feedforward: 256
  num_layers: 2

callbacks:
  push_to_repo: False
  checkpoint_folder: ../saganet
  use_wandb: True

trainer:
  num_gpus: 2
  num_nodes: 1
  gradient_clip_val: 1.0
  max_train_steps: 400000
  gradient_accumulation_steps: 1
  check_val_steps: 1000
  resume: False

optimization:
  learning_rate: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.98
  adam_epsilon: 1e-06
  weight_decay: 0.01